### ISSUE TITLE
priority 2 poll method bug

### ISSUE THREAD

**Issue by at0rvk** [Thibauth/python-pushover#16]
> request.poll()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.4/dist-packages/pushover.py", line 164, in poll
>     request.answer[parameter + "_at"])
> KeyError: 'expired_at'

The polling method tries to use the **expired_at** parameter from pushover's api. This parameter does not exist. The correct parameter is **expires_at**.

**Comment by drachenminister** [comment]
This has already been fixed quite some time ago - try using an up to date version.

See  [https://github.com/Thibauth/python-pushover/commit/8c9c32f9a72b0e49e67e4e5bd7cfcb3565c87597]

**Comment by drachenminister** [comment]
It seems that pip install python-pushover installes an old version so you should install directly from GitHub (see README)

**Comment by Thibauth** [comment]
@drachenminister is correct, the issue was fixed in 8c9c32f9a72b0e49e67e4e5bd7cfcb3565c87597. However, the last release (v0.2) predates this fix, which is why you are experiencing the bug if you are installing from Pypi (for example using `pip install`). You can either:
- install directly from git
- wait until I release v0.3 with the latext fixes on Pypi. This should be sometime next week;  after that `pip install --upragde` should solve your problem.

**Comment by ericbarch** [comment]
Any update on the pip release? The git fix is at least working in the interim :)

**Comment by Thibauth** [comment]
Sorry for the delay. The latest release (0.3) contains the fix (as well as a few other changes). You should be able to get the new release by running `pip install --upgrade python-pushover`.
